on:
  - push
  - pull_request
  - workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-24.04-arm
    env:
      IMAGE_NAME: silvermobility
      REGISTRY: ghcr.io/onesaladleaf

    steps:
    - name: Clone the repository
      uses: actions/checkout@v4

    - name: Build the container
      id: build-container
      uses: redhat-actions/buildah-build@v2
      with:
        image: ${{ env.IMAGE_NAME }}
        tags: latest ${{ github.sha }}
        containerfiles: |
          ./Containerfile

    - name: Build the raw disk image
      run: |
        set -uexo pipefail

        sudo podman run \
          --rm \
          -it \
          --privileged \
          --pull=newer \
          --security-opt label=type:unconfined_t \
          -v ./config.toml:/config.toml:ro \
          -v ./output:/output \
          -v /var/lib/containers/storage:/var/lib/containers/storage \
          quay.io/centos-bootc/bootc-image-builder:latest \
          --type raw \
          --use-librepo=True \
          --rootfs btrfs \
          ${{ steps.build-container.outputs.image }}:latest

    - name: Post-process image artifacts
      run: |
        set -uexo pipefail

        mkdir artifacts/

        sudo kpartx -vafs ./${{ steps.build-raw.outputs.output-directory }}/image/disk.raw
        sudo dd if=/dev/mapper/loop0p1 of=efipart.vfat bs=1M
        sudo dd if=/dev/mapper/loop0p2 of=artifacts/boot.raw bs=1M
        sudo dd if=/dev/mapper/loop0p3 of=artifacts/root.raw bs=1M

        VOLID=$(file efipart.vfat | grep -Eo "serial number 0x.{8}" | cut -d\  -f3)

        truncate -s 268435456 artifacts/esp.raw
        mkfs.vfat -F 32 -S 4096 -n EFI -i $VOLID artifacts/esp.raw

        mkdir -p esp.old esp.new
        sudo mount -o loop efipart.vfat esp.old
        sudo mount -o loop artifacts/esp.raw esp.new

        sudo cp -a esp.old/. esp.new/
        sudo umount esp.old/ esp.new/

        gzip artifacts/*

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: silvermobility
        path: ./artifacts
