name: Build rawhide images
on:
  workflow_dispatch:
  push:
    paths:
      - "devices/**"
      - "desktops/**"
    branches:
      - main

jobs:
  devices:
    name: Build the base device images
    strategy:
      matrix:
        device: [mipad5, oneplus6]
    uses: ./.github/workflows/build.yml
    with:
      image_name: ${{ matrix.device }}-base
      image_tags: rawhide
      base_name: ""
      base_tag: rawhide
      containerfiles: |
        ./devices/${{ matrix.device }}/Containerfile
      context: devices/${{ matrix.device }}
    secrets: inherit

  desktops:
    name: Build the desktop images
    needs: devices
    strategy:
      matrix:
        device: [mipad5, oneplus6]
        desktop: [gnome-desktop, gnome-mobile, phosh]
    uses: ./.github/workflows/build.yml
    with:
      image_name: ${{ matrix.device }}-${{ matrix.desktop }}
      image_tags: rawhide
      base_name: ${{ matrix.device }}-base
      base_tag: rawhide
      containerfiles: |
        ./desktops/${{ matrix.desktop }}/Containerfile
      context: desktops/${{ matrix.desktop }}
    secrets: inherit
