name: Build stable images
on:
  workflow_dispatch:

jobs:
  base:
    name: Build the base image
    uses: ./.github/workflows/build.yml
    with:
      image_name: base
      image_tags: 42 latest
      base_tag: 42
      containerfiles: |
        ./base/Containerfile
      context: base
    secrets: inherit

  phosh:
    name: Build the phosh image
    uses: ./.github/workflows/build.yml
    needs: base
    with:
      image_name: phosh
      image_tags: 42 latest
      base_tag: 42
      containerfiles: |
        ./phosh/Containerfile
      context: phosh
    secrets: inherit

  gnome:
    name: Build the gnome mobile image
    uses: ./.github/workflows/build.yml
    needs: base
    with:
      image_name: gnome-mobile
      image_tags: 42 latest
      registry: ghcr.io/onesaladleaf
      base_tag: 42
      containerfiles: |
        ./gnome-mobile/Containerfile
      context: gnome-mobile
    secrets: inherit
