name: Build stable images
on:
  workflow_dispatch:

jobs:
  devices:
    name: Build the base device images
    strategy:
      matrix:
        device: [mipad5]
    uses: ./.github/workflows/build.yml
    with:
      image_name: ${{ matrix.device }}-base
      image_tags: 42 latest
      base_name: ""
      base_tag: 42
      containerfiles: |
        ./devices/${{ matrix.device }}/Containerfile
      context: devices/${{ matrix.device }}
    secrets: inherit

  desktops:
    name: Build the desktop images
    needs: devices
    strategy:
      matrix:
        device: [mipad5]
        desktop: [gnome-desktop, gnome-mobile, phosh]
    uses: ./.github/workflows/build.yml
    with:
      image_name: ${{ matrix.device }}-${{ matrix.desktop }}
      image_tags: 42 latest
      base_name: ${{ matrix.device }}-base
      base_tag: 42
      containerfiles: |
        ./desktops/${{ matrix.desktop }}/Containerfile
      context: desktops/${{ matrix.desktop }}
    secrets: inherit
