name: Build a container image
on:
  workflow_call:
    inputs:
      image_tag:
        required: true
        type: string
      base_tag:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-24.04-arm

    steps:
    - name: Clone the repository
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Build the container image
      id: build-container
      run: |
        sudo /usr/bin/buildah bud \
            -f ./base/Containerfile \
            --build-arg base_tag=${{ inputs.base_tag }} \
            --format docker \
            --tls-verify=true \
            --cap-add=all \
            --security-opt=label=type:container_runtime_t \
            --device /dev/fuse \
            -t base:${{ inputs.base_tag }}-single \
            ./base

    - name: Rechunk the image
      run: |
        sudo podman run \
            --rm \
            --privileged \
            -v /var/lib/containers:/var/lib/containers \
            quay.io/fedora/fedora-bootc:${{ inputs.base_tag }} \
            /usr/libexec/bootc-base-imagectl rechunk \
                base:${{ inputs.base_tag }}-single \
                base:${{ inputs.image_tag }}

    - name: Log in to the registry
      run: |
        sudo podman login \
            ${{ vars.REGISTRY }} \
            -u ${{ secrets.QUAY_USERNAME }} \
            -p ${{ secrets.QUAY_TOKEN }} \
            --verbose

    - name: Push to the repository
      run: |
        sudo podman push \
            --quiet \
            --digestfile base-${{ inputs.image_tag }}_digest.txt \
            base:${{ inputs.image_tag }} \
            ${{ vars.REGISTRY }}/base:${{ inputs.image_tag }} \
            --tls-verify=true
