name: Build rawhide images
on:
  workflow_dispatch:
  push:
    paths:
      - "base/**"
      - "phosh/**"
      - "gnome-mobile/**"
    branches:
      - main

jobs:
  base:
    name: Build the base image
    uses: ./.github/workflows/build.yml
    with:
      image_name: base
      image_tags: rawhide
      base_tag: rawhide
      containerfiles: |
        ./base/Containerfile
      context: base
    secrets: inherit

  phosh:
    name: Build the phosh image
    uses: ./.github/workflows/build.yml
    needs: base
    with:
      image_name: phosh
      image_tags: rawhide
      base_tag: rawhide
      containerfiles: |
        ./phosh/Containerfile
      context: phosh
    secrets: inherit

  gnome:
    name: Build the gnome mobile image
    uses: ./.github/workflows/build.yml
    needs: base
    with:
      image_name: gnome-mobile
      image_tags: rawhide
      base_tag: rawhide
      containerfiles: |
        ./gnome-mobile/Containerfile
      context: gnome-mobile
    secrets: inherit
