name: Build a container image
on:
  workflow_call:
    inputs:
      image_name:
        required: true
        type: string
      image_tags:
        required: true
        type: string
      base_name:
        required: true
        type: string
      base_tag:
        required: true
        type: string
      containerfiles:
        required: true
        type: string
      context:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-24.04-arm

    steps:
    - name: Clone the repository
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Build the container image
      id: build-container
      uses: redhat-actions/buildah-build@v2
      with:
        image: ${{ inputs.image_name }}
        tags: ${{ inputs.image_tags }}
        containerfiles: ${{ inputs.containerfiles }}
        context: ${{ inputs.context }}
        build-args: |
          base_name=${{ inputs.base_name }}
          base_tag=${{ inputs.base_tag }}
        extra-args: |
          --cap-add=all
          --security-opt=label=type:container_runtime_t
          --device /dev/fuse

    - name: Log in to the registry
      uses: redhat-actions/podman-login@v1
      with:
        registry: ${{ vars.REGISTRY }}
        username: ${{ secrets.QUAY_USERNAME }}
        password: ${{ secrets.QUAY_TOKEN }}

    - name: Push to the repository
      uses: redhat-actions/push-to-registry@v2
      with:
        image: ${{ steps.build-container.outputs.image }}
        tags: ${{ steps.build-container.outputs.tags }}
        registry: ${{ vars.REGISTRY }}
