name: Build rawhide images
on:
  workflow_dispatch:
  push:
    paths:
      - "base/**"
      - "phosh/**"
    branches:
      - main

jobs:
  base:
    name: Build the base image
    uses: ./.github/workflows/build.yml
    with:
      image_name: pocketblue-base
      image_tags: rawhide
      registry: ghcr.io/onesaladleaf
      base_tag: rawhide
      containerfiles: |
        ./base/Containerfile
      context: base

  phosh:
    name: Build the phosh image
    uses: ./.github/workflows/build.yml
    needs: base
    with:
      image_name: pocketblue-phosh
      image_tags: rawhide
      registry: ghcr.io/onesaladleaf
      base_tag: rawhide
      containerfiles: |
        ./phosh/Containerfile
      context: phosh

  gnome:
    name: Build the gnome image
    uses: ./.github/workflows/build.yml
    needs: base
    with:
      image_name: pocketblue-gnome
      image_tags: rawhide
      registry: ghcr.io/onesaladleaf
      base_tag: rawhide
      containerfiles: |
        ./gnome/Containerfile
      context: gnome
