name: Build stable images
on:
  workflow_dispatch:

jobs:
  base:
    name: Build the base image
    uses: ./.github/workflows/build.yml
    with:
      image_name: pocketblue-base
      image_tags: 42 latest
      registry: ghcr.io/onesaladleaf
      base_tag: 42
      containerfiles: |
        ./base/Containerfile
      context: base

  phosh:
    name: Build the phosh image
    uses: ./.github/workflows/build.yml
    needs: base
    with:
      image_name: pocketblue-phosh
      image_tags: 42 latest
      registry: ghcr.io/onesaladleaf
      base_tag: 42
      containerfiles: |
        ./phosh/Containerfile
      context: phosh

  gnome:
    name: Build the gnome image
    uses: ./.github/workflows/build.yml
    needs: base
    with:
      image_name: pocketblue-gnome
      image_tags: 42 latest
      registry: ghcr.io/onesaladleaf
      base_tag: 42
      containerfiles: |
        ./gnome/Containerfile
      context: gnome
