name: containers 42-dev
on:
  push:
    paths:
      - 'base/**'
      - 'devices/**'
      - 'desktops/**'
    branches-ignore:
      - main
  workflow_dispatch: {}

jobs:
  containers_dev:
    name: containers ${{ github.ref_name }}
    permissions:
      packages: write
    secrets: inherit
    uses: ./.github/workflows/helper-containers-devices-desktops.yml
    with:
      from_tag: '42'
      push_tags: 42-${{ github.ref_name }}
