name: containers 42-dev
on:
  push:
    paths:
      - 'base/**'
      - 'devices/**'
      - 'desktops/**'
    branches-ignore:
      - main
  workflow_dispatch: {}

jobs:
  containers_dev:
    name: containers ${{ github.ref_name }}
    permissions:
      packages: write
    secrets: inherit
    uses: ./.github/workflows/helper-containers-devices-desktops.yml
    with:
      from_tag_fedora_bootc: '42'
      from_tag_pocketblue: 42-${{ github.ref_name }}
      push_tag: 42-${{ github.ref_name }}
      expires_after: 3w
