name: containers 42
on:
  push:
    paths:
      - 'base/**'
      - 'devices/**'
      - 'desktops/**'
    branches:
      - main
  workflow_dispatch: {}

jobs:
  containers_42:
    name: containers 42
    permissions:
      packages: write
    secrets: inherit
    uses: ./.github/workflows/helper-containers-devices-desktops.yml
    with:
      from_tag_fedora_bootc: '42'
      from_tag_pocketblue: '42'
      push_tag: 42
      latest: true
