name: containers input
on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'branch, example: 43'
        required: false
        default: '43'
        type: string

jobs:
  containers:
    name: containers ${{inputs.branch}}
    permissions:
      packages: write
    secrets: inherit
    uses: ./.github/workflows/helper-containers-devices-desktops.yml
    with:
      from_tag_fedora_bootc: ${{inputs.branch}}
      from_tag_pocketblue: ${{inputs.branch}}
      push_tag: ${{inputs.branch}}
