on:
  workflow_call:
    inputs:
      push_tags:
        required: true
        type: string
      from_tag:
        required: true
        type: string
      from_image:
        required: true
        type: string
      image:
        required: true
        type: string
      containerfile:
        required: true
        type: string
      expires_after:
        required: false
        type: string

jobs:
  build:
    name: ${{ inputs.image }}:${{ inputs.from_tag }}
    runs-on: ubuntu-24.04-arm
    permissions:
      packages: write
    steps:
      - name: Clone the repository
        uses: actions/checkout@v4

      - id: getcontext
        shell: bash
        run: echo "context=$(dirname ${{ inputs.containerfile }})" >> $GITHUB_OUTPUT

      - name: Set tag expiry
        id: expiry
        if: inputs.expires_after != ''
        run: echo "label=quay.expires-after=${{ inputs.expires_after }}" >> $GITHUB_OUTPUT

      - name: Build container
        uses: redhat-actions/buildah-build@v2
        with:
          build-args: from=${{ inputs.from_image }}:${{ inputs.from_tag }}
          image: ${{ inputs.image }}
          context: ${{ steps.getcontext.outputs.context }}
          containerfiles: ${{ inputs.containerfile }}
          tags: ${{ inputs.push_tags }}
          labels: ${{ steps.expiry.outputs.label || '' }}

      - name: Push to registry
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ inputs.image }}
          tags: ${{ inputs.push_tags }}
          registry: ${{ vars.REGISTRY }}
          username: ${{ vars.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_TOKEN }}
