on:
  workflow_call:
    inputs:
      device:
        required: true
        type: string
      image_name:
        required: true
        type: string
      image_tag:
        type: string
        default: '42'
      rootfs:
        type: string
        default: btrfs
      args_7z:
        type: string
        default: ''

jobs:
  build:
    name: ${{ inputs.image_name }}
    runs-on: ubuntu-24.04-arm

    steps:
    - name: Clone the repository
      uses: actions/checkout@v4

    - name: Update 7z
      run: |
        curl -L https://7-zip.org/a/7z2501-linux-arm64.tar.xz | tar -xJf -
        sudo cp 7zzs /bin/7z

    - name: Get device config
      id: conf
      run: |
        cat devices/${{ inputs.device }}/device.conf >> "$GITHUB_OUTPUT"

    - name: Build partition images
      uses: pocketblue/actions/partition-images@main
      with:
        config_file: ./config.toml
        esp_size: ${{ steps.conf.outputs.esp_size }}
        rootfs: ${{ inputs.rootfs }}
        install_dtb: ${{ steps.conf.outputs.install_dtb }}
        registry: ${{ vars.REGISTRY }}
        image_name: ${{ inputs.image_name }}
        image_tag: ${{ inputs.image_tag }}

    - name: Collect artifacts
      env:
        DEVICE: ${{ inputs.device }}
        IMAGE_NAME: ${{ inputs.image_name }}
        IMAGE_TAG: ${{ inputs.image_tag }}
        ARGS_7Z: ${{ inputs.args_7z}}
      run: |
        bash scripts/$DEVICE/artifacts-$DEVICE.sh

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: pocketblue-${{ inputs.image_name }}-${{ inputs.image_tag }}
        path: ./pocketblue-${{ inputs.image_name }}-${{ inputs.image_tag }}.7z
        compression-level: 0
