on:
  workflow_call:
    inputs:
      image_name:
        required: true
        type: string
      image_tag:
        required: true
        type: string
      esp_size:
        required: true
        type: number
      rootfs:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-24.04-arm

    steps:
    - name: Clone the repository
      uses: actions/checkout@v4

    - name: Raw disk image
      id: build-raw
      uses: osbuild/bootc-image-builder-action@v0.0.2
      with:
        config-file: ./config.toml
        image: ${{ vars.REGISTRY }}/${{ inputs.image_name }}:${{ inputs.image_tag }}
        rootfs: ${{ inputs.rootfs }}
        types: |
          raw

    - name: Post-process image artifacts
      env:
        OUTPUT_DIR: ${{ steps.build-raw.outputs.output-directory }}
        ESP_SIZE: ${{ inputs.esp_size }}
        IMAGE_NAME: ${{ inputs.image_name }}
        IMAGE_TAG: ${{ inputs.image_tag }}
      run: |
        sudo apt install -y p7zip
        bash scripts/image.sh
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: pocketblue-${{ inputs.image_name }}-${{ inputs.image_tag }}
        path: ./pocketblue-${{ inputs.image_name }}-${{ inputs.image_tag }}.7z
        compression-level: 0
