on:
  workflow_call:
    inputs:
      from_tag:
        required: true
        type: string
      push_tags:
        required: true
        type: string

jobs:
  base:
    permissions:
      packages: write
    secrets: inherit
    uses: ./.github/workflows/helper-containers.yml
    with:
      push_tags: ${{ inputs.push_tags }}
      from_tag: ${{ inputs.from_tag }}
      from_image: quay.io/fedora/fedora-bootc
      image: base
      containerfile: base/Containerfile
  devices:
    needs: base
    permissions:
      packages: write
    secrets: inherit
    strategy:
      matrix:
        device: [oneplus6, mipad5]
    uses: ./.github/workflows/helper-containers.yml
    with:
      push_tags: ${{ inputs.push_tags }}
      from_tag: ${{ inputs.from_tag }}
      from_image: ${{ vars.REGISTRY }}/base
      image: ${{ matrix.device }}-base
      containerfile: devices/${{ matrix.device }}/Containerfile
  desktops:
    needs: devices
    permissions:
      packages: write
    secrets: inherit
    strategy:
      matrix:
        device: [oneplus6, mipad5]
        desktop: [gnome-mobile, gnome-desktop, phosh]
    uses: ./.github/workflows/helper-containers.yml
    with:
      push_tags: ${{ inputs.push_tags }}
      from_tag: ${{ inputs.from_tag }}
      from_image: ${{ vars.REGISTRY }}/${{ matrix.device }}-base
      image: ${{ matrix.device }}-${{ matrix.desktop }}
      containerfile: desktops/${{ matrix.desktop }}/Containerfile
