on:
  workflow_call:
    inputs:
      device:
        required: true
        type: string
      fedora_branch:
        required: true
        type: string
      pocketblue_tag:
        required: true
        type: string
      latest:
        required: false
        type: boolean
        default: false
      expires_after:
        required: false
        type: string

jobs:
  device-base:
    name: '${{ inputs.device }}: base'
    permissions:
      packages: write
    secrets: inherit
    uses: ./.github/workflows/helper-build-container.yml
    with:
      push_tag: ${{ inputs.pocketblue_tag }}
      from_tag: ${{ inputs.pocketblue_tag }}
      from_image: ${{ vars.REGISTRY }}/base
      image: ${{ inputs.device }}-base
      containerfile: devices/${{ inputs.device }}/Containerfile
      latest: ${{ inputs.latest }}
      expires_after: ${{ inputs.expires_after }}

  desktops:
    name: '${{ inputs.device }}: desktops'
    needs: device-base
    permissions:
      packages: write
    secrets: inherit
    strategy:
      matrix:
        desktop: [ gnome-mobile, gnome-desktop, phosh, plasma-desktop, plasma-mobile ]
    uses: ./.github/workflows/helper-build-container.yml
    with:
      push_tag: ${{ inputs.pocketblue_tag }}
      from_tag: ${{ inputs.pocketblue_tag }}
      from_image: ${{ vars.REGISTRY }}/${{ inputs.device }}-base
      image: ${{ inputs.device }}-${{ matrix.desktop }}
      containerfile: desktops/${{ matrix.desktop }}/Containerfile
      latest: ${{ inputs.latest }}
      expires_after: ${{ inputs.expires_after }}
      rechunk: true
