name: images oneplus6
on:
  workflow_dispatch:

jobs:
  oneplus6:
    strategy:
      matrix:
        desktop: [gnome-mobile, phosh]
    uses: ./.github/workflows/helper-images.yml
    with:
      device: oneplus6
      image_name: oneplus6-${{ matrix.desktop }}
      image_tag: 42
      esp_size: 268435456
      rootfs: btrfs
