name: images release
permissions:
  contents: write
on:
  workflow_dispatch: {}

jobs:
  images_build:
    name: building ${{ matrix.device.name }}-${{ matrix.desktop }}
    strategy:
      fail-fast: false
      matrix:
        device:
          - name: mipad5
          - name: oneplus6
        desktop: [gnome-desktop, gnome-mobile, phosh, plasma-desktop, plasma-mobile]

    uses: ./.github/workflows/build-image.yml
    with:
      device: ${{ matrix.device.name }}
      image_name: ${{ matrix.device.name }}-${{ matrix.desktop }}
      args_7z: -mmt=1 -md=1500m

  publish_release:
    name: publish release
    needs: images_build
    runs-on: ubuntu-latest
    steps:
      - name: get_tag
        id: get_tag
        run: |
          podman pull quay.io/pocketblue/base:42
          export full_tag=$(podman inspect quay.io/pocketblue/base:42 --format '{{ index .Config.Labels "org.opencontainers.image.version" }}')
          echo release_tag=$(echo $full_tag | cut -d. -f1-2) >> $GITHUB_OUTPUT
      - uses: actions/download-artifact@v4
        with:
          pattern: pocketblue-*
          merge-multiple: true
          path: dist
      - name: check sizes
        run: |
          du -h dist/*
          du dist/*
      - uses: svenstaro/upload-release-action@v2
        with:
          tag: ${{ steps.get_tag.outputs.release_tag }}
          file: dist/pocketblue-*.7z
          file_glob: true
          overwrite: true
          body: |
            recommended image for mipad5: [gnome-desktop](https://github.com/pocketblue/pocketblue/releases/download/${{ steps.get_tag.outputs.release_tag }}/pocketblue-mipad5-gnome-desktop-42.7z)
            recommended image for oneplus6: [gnome-mobile](https://github.com/pocketblue/pocketblue/releases/download/${{ steps.get_tag.outputs.release_tag }}/pocketblue-oneplus6-gnome-mobile-42.7z)
