name: images oneplus6
on:
  workflow_dispatch:

jobs:
  oneplus6:
    strategy:
      matrix:
        desktop: [gnome-desktop, gnome-mobile, phosh, plasma-desktop, plasma-mobile]
    uses: ./.github/workflows/helper-images.yml
    with:
      device: oneplus6
      image_name: oneplus6-${{ matrix.desktop }}
      esp_size: 268435456
