name: Raw images for Mi Pad 5
on:
  workflow_dispatch:

jobs:
  mipad5:
    strategy:
      matrix:
        desktop: [gnome-desktop, gnome-mobile, phosh]
    uses: ./.github/workflows/raw-image.yml
    with:
      image_name: mipad5-${{ matrix.desktop }}
      image_tag: 42
      esp_size: 536870912
      rootfs: ext4
